dist: trusty
sudo: required

matrix:
  fast_finish: true
  include:
   - os: linux
     env: LINUX=ubuntu:16.04
     sudo: required
     language: python
     python: "3.5"
   - os: linux
     env: LINUX=ubuntu:18.04
     sudo: required
     language: python
     python: "3.6"
   - os: linux  # this is python 3.7
     env: LINUX=ubuntu:19.10
     sudo: required
     language: python
     python: "3.6"
   - os: linux  # stable
     env: LINUX=debian:stretch
     sudo: required
     language: python
     python: "3.5"
   - os: linux  # testing; this is actually python 3.7
     env: LINUX=debian:buster
     sudo: required
     language: python
     python: "3.6"
   - os: osx
     language: generic
     osx_image: xcode8.3  # OS 10.12
   - os: osx
     language: generic
     osx_image: xcode8  # OS 10.11
   - os: osx
     language: generic
     osx_image: xcode6.4  # OS 10.10

services:
  - docker

before_install:
  - git clone --recursive --branch ${TRAVIS_BRANCH} https://github.com/missionpinball/mpf-mc.git _mpf-mc || git clone --recursive --branch `python3 get_version.py` https://github.com/missionpinball/mpf-mc.git _mpf-mc || git clone --recursive --branch dev https://github.com/missionpinball/mpf-mc.git _mpf-mc;
  - git clone --branch ${TRAVIS_BRANCH} https://github.com/missionpinball/mpf-debian-installer.git _mpf_installer || git clone --recursive --branch `python3 get_version.py` https://github.com/missionpinball/mpf-debian-installer.git _mpf_installer || git clone --recursive --branch dev https://github.com/missionpinball/mpf-debian-installer.git _mpf_installer;

install:
- if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      curl -sS https://www.python.org/ftp/python/3.5.4/python-3.5.4-macosx10.6.pkg > python-3.5.4-macosx10.6.pkg;
      sudo installer -pkg python-3.5.4-macosx10.6.pkg -target /;
      curl -sS https://bootstrap.pypa.io/get-pip.py > get-pip.py;
      sudo python3 get-pip.py;
      pip3 install .;
  fi;

script:
- if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
    docker run -v $PWD:$PWD -w $PWD $LINUX /bin/sh -c "_mpf_installer/install-mpf-dependencies && pip3 install --upgrade coveralls && pip3 install prospector==1.1.7 && pip3 install . && export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/_mpf-mc && prospector && coverage3 run --concurrency=thread -m unittest discover -s mpf/tests && python3 test_regression.py;";
  fi;
- if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      export PYTHONPATH=$PYTHONPATH:$(pwd)/_mpf-mc;
      python3 -m unittest discover mpf/tests;
  fi;

after_success:
- if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      coveralls;
  fi;

