environment:

  global:
    MPF_VERSION: 0.30

  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"

  pypi_user:
    secure: kxNKBuVMdOz6LjJPQb7PMQ==

  pypi_password:
    secure: nmmwU7UgFbrGUJwIr0Vo6cHzCuxlvW4vjg9TjkwrjmE=

install:
  - "git submodule update --init --recursive"
  - "%PYTHON%\\python.exe -m pip install -U setuptools wheel pip mock twine"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py test -q"

after_test:
  - "%PYTHON%\\python.exe setup.py sdist --formats=gztar"
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*

deploy_script:
  - "%PYTHON%\\python.exe -m twine upload -u %pypi_user% -p %pypi_password% --skip-existing dist/*"
