# config_version=2

Scriptlets:
    attract.Attract
    deadworld.Deadworld
    add_a_ball.AddABall

Config:
    - dmd.yaml
    - game_logic.yaml
    - hardware.yaml
    - languages.yaml
    - sound.yaml
    - window.yaml
