# Instructions for this config file:
# https://missionpinball.com/docs/configuration-file-reference/

Flippers:
    LowerLeft:
        main_coil: flipperLwLMain
        hold_coil: flipperLwLHold
        activation_switch: flipperLwL
        eos_switch: flipperLwL_EOS
        #use_eos: True
        #hold_pwm:
        #tags:
        label: Left Main Flipper
    LowerRight:
        main_coil: flipperLwRMain
        hold_coil: flipperLwRHold
        activation_switch: flipperLwR
        eos_switch: flipperLwR_EOS
        label: Right Main Flipper
    UpperLeft:
        main_coil: flipperUpLMain
        hold_coil: flipperUpLHold
        activation_switch: flipperUpL
        eos_switch: flipperUpL_EOS
        label: Upper Left Flipper
    UpperRight:
        main_coil: flipperUpRMain
        hold_coil: flipperUpRHold
        activation_switch: flipperUpR
        eos_switch: flipperUpR_EOS
        label: Upper Right Flipper
        
Autofire Coils:
    # label
        # coil - name
        # switch - name
        # switch activity - 0 = inactive, 1 = active
        # coil action - enable, pulse, pwm, pulse_pwm, disable
        # delay - ms before firing
        # recycle time - ms before being allowed to fire again
        
    SlingL:
        coil: slingL
        switch: slingL
    SlingR:
        coil: slingR
        switch: slingR
        
DropTargets:
    J:
        switch: dropTargetJ
        light: dropTargetJ
        reset_coil: resetDropTarget
    U:
        switch: dropTargetU
        light: dropTargetU
        reset_coil: resetDropTarget
    D:
        switch: dropTargetD
        light: dropTargetD
        reset_coil: resetDropTarget
        knockdown_coil: tripDropTarget
    G:
        switch: dropTargetG
        light: dropTargetG
        reset_coil: resetDropTarget
    E:
        switch: dropTargetE
        light: dropTargetE
        reset_coil: resetDropTarget

DropTargetBanks:
    Judge:
        drop_targets: J, U, G, E
        reset_coils: resetDropTarget
        reset_events:
            ball_starting: 0
            drop_targets_Judge_complete: 1s
        complete_show: drop_target_complete

Targets:  # Not yet implemented
    QuestionMark:
        switch: mystery
        light: mystery
    AdvanceCrime:
        switch: threeBankTargets
        light: advanceCrimeLevel
    LeftExtraBall:
        switch: leftScorePost
        light: ExtraBall
    RightExtraBall:
        switch: rightTopPost
        light: ExtraBall

TargetGroups:
    pf_standups:
        targets: QuestionMark, AdvanceCrime, LeftExtraBall, RightExtraBall
        rotate_left_events: sw_left_flipper
        rotate_right_events: sw_right_flipper
        

Diverters:
    deadWorld:
        coil: diverter
        type: hold
        timeout: 3s
        activation_switch: leftRampEnter
        enable_events: shot_LeftRamp
        disable_events: ball_ending
        disable_switch: leftRampToLock
        target_when_enabled:
            type: ball_device
            name: deadworld
        target_when_disabled:
            type: playfield
            name:
        

BallDevices:

    trough:
        tags: trough, home, drain
        label: Main Trough
        ball_switches: trough1, trough2, trough3, trough4, trough5, trough6, troughJam
        ball_capacity: 6
        entrance_count_delay: 0.5s
        eject_coil: trough
        eject_switch: trough6
        exit_count_delay: 2s
        confirm_eject_type: device
        confirm_eject_target: shooterLaneR

    shooterLaneR:
        tags: ball_add_live
        label: Right Plunger Lane
        ball_switches: shooterR
        eject_switch: shooterR
        entrance_count_delay: 0.3s
        eject_coil: shooterR
        confirm_eject_type: playfield
        feeder_device: trough

    shooterLaneL:
        label: Left Plunger Lane
        ball_switches: ShooterLaneL
        eject_switch: ShooterLaneL
        entrance_count_delay: 0.3s
        eject_coil: shooterL
        confirm_eject_type: count
        exit_count_delay: 0.5s

    SniperVUK:
        label: Sniper Tower VUK
        ball_switches: popperR
        eject_switch: popperR
        entrance_count_delay: 0.3s
        eject_coil: popperR
        confirm_eject_type: count
        exit_count_delay: 0.5s

    HallOfJusticeVUK:
        label: Hall of Justice VUK
        ball_switches: popperL
        eject_switch: popperL
        entrance_count_delay: 0.3s
        eject_coil: popperL
        confirm_eject_type: count
        exit_count_delay: 0.5s

    
            