Languages:
    English
    German
    French

LanguageStrings:
    French:
        PRESS START: APPUYEZ SUR START
        FREE PLAY: JEU GRATUIT
        PLAYER: JOUEUR
        BALL: BALLE
    German:
        PRESS START: START DRUEKEN
        FREE PLAY: FREISPIEL
        PLAYER: SPIELER
        BALL: BALL

LanguageSounds:
    French:
        slingshot:
            file: le_slingshot.ogg