# config_version=1
SoundSystem:
    tracks:
        voice:
            volume: 1
            priority: 2
            simultaneous_sounds: 1
            preload: no
        sfx:
            volume: 1
            priority: 1
            preload: no
            simultaneous_sounds: 3
    stream:
        name: music
        priority: 0
        

    buffer: 512
    frequency: 44100
    channels: 1
    initial_volume: 1
    volume_steps: 20