

Window:
    width: 800
    height: 600
    title: Mission Pinball Framework
    resizable: yes
    frame: yes
    fullscreen: no
    fps: auto
    quit_on_close: True
    elements:

          - type: VirtualDMD
            width: 512
            height: 128
            h_pos: center
            v_pos: center
            pixel_color: ff5500
            dark_color: 220000
            layer: 1
            pixel_spacing: 2

          - type: Text
            font: tall title
            text: JUDGE DREDD
            h_pos: right
            v_pos: bottom
            y: -10
            x: -20
            size: 60
            antialias: yes
            layer: 1
            color: ee9900

        #Background:
        #    type: Image
        #    image: mpf_background
        #    x: 0
        #    y: 0
        #    layer: 0

          - type: Shape
            shape: box
            width: 514
            height: 130
            layer: 2
            thickness: 2
            v_pos: center
            h_pos: center
            color: 00ff00

          #- type: Movie
          #  movie: torches
          #  repeat: True
          #  layer: 0

Config:
    - keymap.yaml