Hardware:
    Platform: p_roc
    DriverBoards: wpc

Game:
    player_controlled_eject_tag: launch

Switches:
    leftFlipperButton:
        number: SF4
    rightFlipperButton:
        number: SF6
    trough1:
        number: S81
        type: NC
    trough2:
        number: S82
        type: NC
    trough3:
        number: S83
        type: NC
    trough4:
        number: S84
        type: NC
    trough5:
        number: S85
        type: NC
    trough6:
        number: S86
        type: NC
    troughJam:
        number: S87
        type: NC
    plungerLane:
        number: S41
    start:
        number: S13
        tags: start
    plungerLaunch:
        number: S12
        tags: launch

Coils:
    flipperLeftMain: 
        number: FLLM
        pulse_ms: 20
    flipperLeftHold: 
        number: FLLH
    flipperRightMain: 
        number: FLRM
        pulse_ms: 20
    flipperRightHold: 
        number: FLRH
    troughEject:
        number: C13
        pulse_ms: 20
    plungerEject:
        number: C08
        pulse_ms: 20

Flippers:
    leftFlipper:
        main_coil: flipperLeftMain
        hold_coil: flipperLeftHold
        activation_switch: leftFlipperButton
    rightFlipper:
        main_coil: flipperRightMain
        hold_coil: flipperRightHold
        activation_switch: rightFlipperButton

Plugins:
    - keyboard.Keyboard

Keyboard:
    z:
        switch: leftFlipperButton
    /:
        switch: rightFlipperButton
    1:
        switch: trough1
        toggle: true
    2:
        switch: trough2
        toggle: true
    3:
        switch: trough3
        toggle: true
    4:
        switch: trough4
        toggle: true
    5:
        switch: trough5
        toggle: true
    6:
        switch: trough6
        toggle: true
    p:
        switch: plungerLane
        toggle: true
    s:
        switch: start
    L:
        switch: plungerLaunch
    

BallDevices:
    trough:
        ball_switches: trough1, trough2, trough3, trough4, trough5, trough6, troughJam
        entrance_count_delay: 300ms
        eject_coil: troughEject
        eject_switch: trough6
        confirm_eject_type: device
        target_device: plunger
        tags: trough, home, drain
    plunger:
        ball_switches: plungerLane
        entrance_count_delay: 300ms
        exit_count_delay: 3s
        eject_switch: plungerLane
        eject_coil: plungerEject
        confirm_eject_type: count
        tags: ball_add_live

DMD:
    physical: yes
    width: 128
    height: 32

Window:
    title: My Awesome Game!
    elements:
        onscreen_dmd:
            type: VirtualDMD
            width: 512
            height: 128
            h_pos: center
            v_pos: center
            pixel_color: ff6600
            dark_color: 220000
            pixel_spacing: 1
        dmd_frame:
            type: Shape
            shape: box
            width: 516
            height: 132
            color: aaaaaa
            thickness: 2
        Title:
            type: Text
            font: tall title
            text: MY AWESOME GAME
            h_pos: center
            v_pos: top
            y: 60
            size: 100
            antialias: yes
            layer: 1
            color: ee9900

SlidePlayer:
    machineflow_Attract_start:
        type: Text
        text: PRESS START
    ball_live_added:
        type: Text
        text: BALL LIVE!
    ball_started:
        type: Text
        text: PLAYER %player BALL %ball
    player_add_success:
        type: Text
        text: PLAYER %num ADDED