# config_version=2
mode:
    start_events: ball_starting
    priority: 100
    code: base.Base

slide_player:
    mode_base_started:
      - type: Text
        text: "%score%"
        number_grouping: true
        min_digits: 2
        v_pos: center
      - type: Text
        text: PLAYER %number%
        v_pos: bottom
        h_pos: left
        font: small
      - type: Text
        text: BALL %ball%
        v_pos: bottom
        h_pos: right
        font: small

    player_add_success:
      - type: text
        text: PLAYER %num ADDED
        expire: 2s
        priority: 1

sound_player:
    waiting to plunge loop:
        sound: waiting to plunge loop
        start_events: mode_base_started
        stop_events: sw_plunger
        loops: -1
        volume: 0.5
    background music:
        start_events: sw_plunger
        stop_events: mode_base_stopping, balldevice_elevator_ball_enter
        sound: base background music
        loops: -1
        volume: .5
    ramp 1 fx:
        start_events: sw_ramp_1
        sound: ramp 1
    ramp 2 fx:
        start_events: sw_ramp_2
        sound: ramp 2
    standup lit:
        start_events: shots_standups_lit_hit
        sound: standup hit lit
    standup unlit:
        start_events: shots_standups_unlit_hit
        sound: standup hit unlit
    little metal:
        start_events: sw_slingshot
        sound: little metal
    jets:
        start_events: sw_jet
        sound: medium metal

show_player:
    left_orbit_default_unlit_hit:
        show: left orbit

scoring:
    left_orbit_unlit_hit:
        Score: 1000000
    left_ramp_default_unlit_hit:
        Score: 1000000
    side_ramp_default_unlit_hit:
        Score: 2000000
    right_ramp_default_unlit_hit:
        Score: 1000000
    right_orbit_default_unlit_hit:
        Score: 1500000
    center_ramp_default_unlit_hit:
        Score: 250000
    sw_slingshot:
        Score: 5170
    sw_jet:
        Score: 75020
    sw_outlane:
        Score: 24440
    sw_inlane:
        Score: 47650
    standups_default_lit_hit:
        Score: 10000
    standups_default_unlit_hit:
        Score: 50000
    standups_default_lit_complete:
        Score: 100000
    rollover_default_lanes_lit_hit:
        Score: 5000
    rollover_default_lanes_unlit_hit:
        Score: 45000
    rollover_default_lanes_lit_complete:
        Score: 375000
    sw_small_car_crash:
        Score: 25000
    sw_big_car_crash:
        Score: 11000
    balldevice_lower_vuk_ball_enter:
        Score: 475000
    balldevice_upper_vuk_ball_enter:
        Score: 110000
    balldevice_retina_hole_ball_enter:
        Score: 225000

shot_groups:
    rollover_lanes:
        rotate_left_events: sw_left_flipper
        rotate_right_events: sw_right_flipper
    standups:
        profile: default