# config_version=1
Mode:
    start_events: ball_starting
    end_events: start_mode1_acmag
    priority: 200

LightPlayer:
    mode_claw_lit_for_major_mode_started:
        lights: l_claw_ready
        script: flash
        tocks_per_sec: 4
        repeat: yes
    balldevice_elevator_ball_enter:
        lights: l_claw_ready
        script: "off"

LogicBlocks:
    Accruals:
        enable_the_claw:
            events: mode_claw_lit_for_major_mode_started
            events_when_complete: light_claw
        start_acmag:
            events: sw_acmag
            events_when_complete: start_mode1_acmag

SlidePlayer:
    balldevice_elevator_ball_enter:
        type: text
        text: PICK YOUR MODE
    