# config_version=2

# Base game mode for Aztec

Mode:
    start_events: ball_starting
    priority: 100

slide_player:
    player_score:
      - type: Text
        text: "%value"
        number_grouping: true
        v_pos: center
      - type: Text
        text: PLAYER %number%
        v_pos: bottom
        h_pos: left
        font: small
      - type: Text
        text: BALL %ball%
        v_pos: bottom
        h_pos: right
        font: small

    mode_base_started:
      - type: Text
        text: "%score%"
        number_grouping: true
        min_digits: 2
        v_pos: center
      - type: Text
        text: PLAYER %number%
        v_pos: bottom
        h_pos: left
        font: small
      - type: Text
        text: BALL %ball%
        v_pos: bottom
        h_pos: right
        font: small

    player_add_success:
      - type: text
        text: PLAYER %num ADDED
        expire: 2s
        priority: 1

Shots:
    pops:
        Switch: leftPop, rightPop, bottomPop
    slings:
        Switch: leftSling, rightSling

Scoring:
    targets_upperLanes_lit_complete:
        Score: 5000
    targets_upperLanes_lit_hit:
        Score: 100
    targets_upperLanes_unlit_hit:
        Score: 1000
    shot_pops:
        Score: 150
    shot_slings:
        Score: 10
    balldevice_ballLock_ball_enter:
        Score: 2500
    target_right1_lit:
        Score: 50
    target_right2_lit:
        Score: 50
    target_left1_lit:
        Score: 50
    target_left2_lit:
        Score: 50
    target_middle_lit:
        Score: 50
    target_upperLeft_lit:
        Score: 50
    target_right1_unlit:
        Score: 50
    target_right2_unlit:
        Score: 250
    target_left1_unlit:
        Score: 250
    target_left2_unlit:
        Score: 250
    target_middle_unlit:
        Score: 250
    target_upperLeft_unlit:
        Score: 250

sound_player:
    drain:
        sound: fail
        start_events: ball_drain
    slingshot:
        sound: big metal 
        start_events: shot_slings
    pops:
        sound: little metal
        start_events: shot_pops
    standup_lit:
        sound: standup hit lit
        start_events: target_left1_lit_hit, target_left2_lit_hit
    standup_unlit:
        sound: standup hit unlit
        start_events: target_left1_unlit_hit, target_left2_unlit_hit
    spinner:
        sound: medium metal
        start_events: target_spinner_unlit