#config_version=2
Mode:
    start_events: both_ramps_made
    stop_events: ball_ending
    priority: 200

Scoring:
    shot_RightRamp:
        Score: 50000
        Block: yes
    shot_LeftRamp:
        Score: 50000
        Block: yes

slide_player:
    mode_both_ramps_made_started:
      - type: Text
        text: SHOOT RAMP FOR 50K