3:
  
  section_deprecations:
    - max balls
  
  section_warnings:
    - path: shots
      url: "https://missionpinball.com/docs/configuration-file-reference/config-version-3/"
    - path: drop_targets
      url: "https://missionpinball.com/docs/configuration-file-reference/config-version-3/"
    - path: drop_target_banks
      url: "https://missionpinball.com/docs/configuration-file-reference/config-version-3/"
  
  section_replacements:
    remove_profile_events: remove_active_profile_events
    targets: shots
    target_groups: shot_groups
    target_profiles: shot_profiles
    switch_activity: reverse_switch
    log_color_changes: debug
    attract_start: mode_attract_started
    balls installed: balls_installed
    min balls: min_balls
    balls per game: balls_per_game
    max players per game: max_players
    steps: states
    step_names_to_rotate: state_names_to_rotate
    step_names_to_not_rotate: state_names_to_not_rotate

  string_replacements:
    _remove_profile: _remove_active_profile
    " target_group_": " shot_group_"
    " target_": " shot_"
    " targets_": " shots_"

2:
  section_replacements:
    assetdefaults: asset_defaults
    autofire coils: autofire_coils
    balldevices: ball_devices
    ballsearch: ball_search
    droptargets: drop_targets
    droptargetbanks: drop_target_banks
    languagestrings: language_strings
    lightplayer: light_player
    lightscripts: light_scripts
    logicblocks: logic_blocks
    ledsettings: led_settings
    machineflow: machine_flow
    machineflow_attract_start: attract_start
    machineflow_attract_stop: attract_stop
    matrixlights: matrix_lights
    mediacontroller: media_controller
    openpixelcontrol: open_pixel_control
    score reels: score_reels
    score reel groups: score_reel_groups
    showplayer: show_player
    slideplayer: slide_player
    soundplayer: sound_player
    soundsystem: sound_system
    switchplayer: switch_player
    targetgroups: target_groups
    virtual platform start active switches: virtual_platform_start_active_switches

  section_warnings:
    - path: targets
      url: "https://missionpinball.com/docs/configuration-file-reference/targets/"
    - path: target_groups
      url: "https://missionpinball.com/docs/configuration-file-reference/targetgroups/"
    - path: drop_targets
      url: "https://missionpinball.com/docs/configuration-file-reference/droptargets/"
    - path: drop_target_banks
      url: "https://missionpinball.com/docs/configuration-file-reference/droptargetbanks/"

  section_deprecations:
    - plugins
